//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by scope.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FRAMESCAN_SAW_PROPPAGE      106
#define ID_NEWVIEW_AREA1                108
#define ID_NEWVIEW_AREA2                109
#define ID_NEWVIEW_AREA3                110
#define ID_NEWVIEW_AREA4                111
#define ID_NEWHISTOGRAM_AREA1           112
#define ID_NEWHISTOGRAM_AREA2           113
#define ID_NEWHISTOGRAM_AREA3           114
#define ID_NEWHISTOGRAM_AREA4           115
#define IDR_MAINFRAME                   128
#define IDR_MDICHILD                    129
#define IDPANE_STATUS                   130
#define IDPANE_PIXELINFO                131
#define IDPANE_CONFIG                   132
#define IDPANE_HISTOGRAMLIMITS          133
#define IDPANE_FRAMECOUNT               134
#define IDD_MAINDIALOG                  202
#define IDD_STORAGE_PROPPAGE            203
#define IDR_CHANNELFRAME                203
#define IDD_FPGAPHOTONCOUNTER_PROPPAGE  204
#define IDD_STACK_PROPPAGE              205
#define IDD_TIMESERIES_PROPPAGE         206
#define IDD_MOVEMENT_PROPPAGE           207
#define IDD_STIMULATION_PROPPAGE        208
#define IDI_ARROWUP                     210
#define IDI_ARROWDOWN                   211
#define IDI_ARROWLEFT                   212
#define IDI_ARROWRIGHT                  213
#define IDD_AREACHOOSE                  213
#define IDR_HISTOGRAMFRAME              214
#define IDD_XYZCONTROL_PROPPAGE         214
#define IDR_LOGBOOK                     216
#define IDD_FPUCONTROL_PROPPAGE         216
#define IDR_HISTOGRAM                   219
#define IDD_PRESETNAME_DIALOG           223
#define IDD_SCANMODES_PROPPAGE          224
#define IDD_SCANMODES_REGULAR_PROPPAGE  224
#define IDD_FRAMESCAN_BIDI_PROPPAGE     225
#define IDD_FRAMESCAN_HOPPER_PROPPAGE   226
#define IDD_FPGADEMULTIPLEXER_PROPPAGE  227
#define IDR_NEWCHANNEL_MENU             227
#define IDD_FPGADIGITALDEMULTIPLEXER_PROPPAGE 227
#define IDR_NEWHISTOGRAM_MENU           228
#define IDD_FRAMESCAN_SLAVE_PROPPAGE    228
#define IDD_NOSCAN_PROPPAGE             228
#define IDD_FPGAANALOGDEMULTIPLEXER_PROPPAGE 229
#define IDD_FPGAANALOGINTEGRATOR_PROPPAGE 230
#define IDD_FPGANOISEOUTPUT_PROPPAGE    231
#define IDD_BEHAVIOR_PROPPAGE           232
#define IDD_DAQMX_PROPPAGE              233
#define IDI_LED_GREEN                   234
#define IDI_LED_RED                     235
#define IDB_COLORCOMBO                  236
#define IDI_ICON1                       238
#define IDI_LED_WARNING                 238
#define IDD_FPGARESONANCESCANNER_PROPPAGE 242
#define IDD_FRAMESCAN_RESONANCE_PROPPAGE 243
#define IDD_FRAMESCAN_RESONANCE_SLAVE_PROPPAGE 245
#define IDC_PIXELX                      1003
#define IDC_SCANSETTINGS_HOLDER         1004
#define IDC_PIXELY                      1004
#define IDC_AUTOSAVE_CHECK              1005
#define IDC_AVERAGES                    1005
#define IDC_EXPERIMENTSETTINGS_HOLDER   1005
#define IDC_FRAMERATE                   1006
#define IDC_SAVELIVE_CHECK              1006
#define IDC_FOLDER_BUTTON               1007
#define IDC_LINERATE                    1007
#define IDC_FRAMETIME                   1008
#define ID_SCAN_CONT                    1009
#define IDC_OVERALL_FRAMERATE           1009
#define ID_STOP                         1010
#define IDC_FOLDER_TEXT                 1011
#define IDC_FPUX                        1011
#define IDC_FPUY                        1012
#define IDC_QUIT                        1015
#define IDC_SCAN_SINGLE                 1016
#define IDC_READCHUNKS                  1018
#define IDC_POCKELS_SLIDER              1023
#define IDC_PIXELTIME                   1024
#define IDC_POCKELS_EDIT                1026
#define IDC_ZOOM_EDIT                   1027
#define IDC_STARTAT_EDIT                1027
#define IDC_STOPAT_EDIT                 1028
#define IDC_ETL_SLIDER                  1028
#define IDC_STARTSTACK_EDIT             1028
#define IDC_STARTHERE_BUTTON            1029
#define IDC_ETL_EDIT                    1029
#define IDC_STOPSTACK_EDIT              1029
#define IDC_STOPHERE_BUTTON             1030
#define IDC_SPACING_EDIT                1031
#define IDC_SLICES_LIST                 1032
#define IDC_STARTSTACKHERE_BUTTON       1032
#define IDC_STARTKHERE_BUTTON           1032
#define IDC_RECALC_BUTTON               1033
#define IDC_FRAMES_EDIT                 1034
#define IDC_TOTALTIME_EDIT              1035
#define IDC_STARTSTACK_BUTTON           1037
#define IDC_STARTTIMESERIES_BUTTON      1038
#define IDC_POSX_EDIT                   1039
#define IDC_POSY_EDIT                   1040
#define IDC_ONSET                       1040
#define IDC_POSZ_EDIT                   1041
#define IDC_DURATION                    1041
#define IDC_ONTIME                      1042
#define IDC_OFFTIME                     1043
#define IDC_ENABLE                      1044
#define IDC_FPUDOWN                     1052
#define IDC_FPUUP                       1053
#define IDC_FPULEFT                     1054
#define IDC_FPURIGHT                    1055
#define IDC_AREA1                       1056
#define IDC_AREA2                       1057
#define IDC_TRIGGERED                   1057
#define IDC_FIRSTTRIGGERED              1057
#define IDC_AREA3                       1058
#define IDC_FORALLAREAS_CHECK           1058
#define IDC_AREA4                       1059
#define IDC_PIXELTIME_SLIDER            1059
#define IDC_ALLTRIGGERED                1059
#define IDC_ZSTAGE_RADIO                1060
#define IDC_ETL_RADIO                   1061
#define IDC_ZMOVEMENT_GROUP             1062
#define IDC_MOVEMENTSETTINGS_HOLDER     1064
#define IDC_ETLCALIBRATIONFILE_EDIT     1065
#define IDC_XROT_EDIT                   1065
#define IDC_NAME_EDIT                   1065
#define IDC_CALIBRATIONFILE_BUTTON      1066
#define IDC_YROT_EDIT                   1066
#define IDC_SETZERO_BUTTON              1067
#define IDC_SETXYZERO_BUTTON            1068
#define IDC_STANDAINFOS_EDIT            1069
#define IDC_XOFFSET_EDIT                1069
#define IDC_YOFFSET_EDIT                1070
#define IDC_PRESETS_COMBO               1081
#define IDC_SAVEPRESET_BUTTON           1082
#define IDC_SCANNERDELAY_EDIT           1084
#define IDC_SCANNERDELAY_SLIDER         1085
#define IDC_FRAME_SAWTOOTH_RADIO        1088
#define IDC_FRAME_REGULAR_SAWTOOTH_RADIO 1088
#define IDC_FRAME_BIDI_RADIO            1089
#define IDC_FRAME_REGULAR_BIDI_RADIO    1089
#define IDC_FRAME_HOPPER_RADIO          1090
#define IDC_FRAME_PLANEHOPPER_RADIO     1090
#define IDC_FRAME_REGULAR_PLANEHOPPER_RADIO 1090
#define IDC_XCUTOFF_EDIT                1091
#define IDC_FRAME_PLANEHOPPER_RADIO2    1091
#define IDC_LINE_STRAIGHT_RADIO         1091
#define IDC_LINE_REGULAR_STRAIGHT_RADIO 1091
#define IDC_YCUTOFF_EDIT                1092
#define IDC_AREAS_LIST                  1092
#define IDC_XRETRACE_EDIT               1093
#define IDC_YRETRACE_EDIT               1094
#define IDC_YTURN_EDIT                  1094
#define IDC_PLANES_LIST                 1095
#define IDC_ADDPLANE_BUTTON             1096
#define IDC_DELETEPLANE_BUTTON          1097
#define IDC_TOHOSTOVERFLOW1_BUTTON      1098
#define IDC_INTERLOOPOVERFLOW_BUTTON    1099
#define IDC_USETIFFTAGS                 1099
#define IDC_INTERLOOPTIMEOUT_BUTTON     1100
#define IDC_INTERLOOPTIMEOUT1_BUTTON    1100
#define IDC_COMPRESSTIFF                1100
#define IDC_ACQUIRING_BUTTON            1101
#define IDC_TOHOSTOVERFLOW2_BUTTON      1102
#define IDC_OVERRANGE_BUTTON            1102
#define IDC_INTERLOOPTIMEOUT2_BUTTON    1103
#define IDC_TOHOSTOVERFLOWA1CH1_BUTTON  1103
#define IDC_OVERRANGE_BUTTON2           1103
#define IDC_TOHOSTOVERFLOWA1CH2_BUTTON  1104
#define IDC_TOHOSTOVERFLOWA2CH1_BUTTON  1105
#define IDC_POCKELS_UPDOWN              1105
#define IDC_TOHOSTOVERFLOWA2CH2_BUTTON  1106
#define IDC_LASERFREQ_EDIT              1107
#define IDC_RESETACQ_BUTTON             1108
#define IDC_COMBO1                      1109
#define IDC_TESTCOMBO                   1109
#define IDC_ZOOM_SCROLL                 1111
#define IDC_PIXELTIME_SCROLL            1113
#define IDC_POCKELS_SCROLL              1114
#define IDC_FASTZ_SCROLL                1115
#define IDC_FASTZ_EDIT                  1116
#define IDC_SCROLLBAR1                  1117
#define IDC_SCANNERDELAY_SCROLL         1117
#define IDC_DELETEPRESET_BUTTON         1118
#define IDC_STATIC_HEADING              1119
#define IDC_REPEATS_EDIT                1120
#define IDC_BETWEENREPEATS_EDIT         1121
#define IDC_LIST1                       1121
#define IDC_OVERALLTIME_EDIT            1122
#define IDC_LIST2                       1123
#define IDC_MFCBUTTON1                  1125
#define IDC_LAMBDA_EDIT                 1126
#define IDC_LAMBDA_STATIC               1127
#define IDC_XTURN_EDIT                  1128
#define IDC_STACK_PROGRESS              1128
#define IDC_FRAMES_PROGRESS             1129
#define IDC_PROGRESS2                   1130
#define IDC_REPEATS_PROGRESS            1130
#define IDC_TOHOSTOVERFLOWA1_BUTTON     1131
#define IDC_TOHOSTOVERFLOWA2_BUTTON     1132
#define IDC_FPUX_EDIT                   1133
#define IDC_FPUY_EDIT                   1134
#define IDC_PIXELTIME_EDIT              1135
#define IDC_PIXELX_EDIT                 1136
#define IDC_PIXELY_EDIT                 1137
#define IDC_AVERAGES_EDIT               1138
#define IDC_COUNTHIGH_RADIO             1139
#define IDC_ASPECTRATIOX_EDIT           1139
#define IDC_RADIO2                      1140
#define IDC_COUNTPULSES_RADIO           1140
#define IDC_FPUDIAGRAM                  1140
#define IDC_UNLIMITED_RADIO             1140
#define IDC_STARTBEHAVIOR_BUTTON        1141
#define IDC_ASPECTRATIOY_EDIT           1141
#define IDC_MODEGATED_RADIO             1142
#define IDC_AVERAGES_EDIT2              1142
#define IDC_EDIT1                       1143
#define IDC_BITSHIFTCH1_EDIT            1144
#define IDC_BASELINECH1_EDIT            1145
#define IDC_DAQMXVERSION_EDIT           1145
#define IDC_BITSHIFTCH2_EDIT            1146
#define IDC_CUTOFFCH1_EDIT              1146
#define IDC_BASELINECH2_EDIT            1147
#define IDC_BITSHIFTA2CH1_EDIT          1148
#define IDC_BITSHIFTA2CH2_EDIT          1149
#define IDC_BITSHIFTA1CH1_EDIT          1150
#define IDC_BITSHIFTA1CH2_EDIT          1151
#define IDC_TRIALS_EDIT                 1152
#define IDC_CUTOFFCH1_EDIT2             1152
#define IDC_CUTOFFCH2_EDIT              1152
#define IDC_CHECK1                      1153
#define IDC_SQUAREPIXELS_CHECK          1153
#define IDC_WAITSTORAGE_EDIT            1154
#define IDC_FRAME_RESONANT_BIDI_RADIO   1154
#define IDC_WAITDISPLAY_EDIT            1155
#define IDC_FRAME_RESONANT_PLANEHOPPER_RADIO 1155
#define IDC_HISTRANGE1_EDIT				1156
#define IDC_HISTRANGE2_EDIT				1157
#define IDC_ADDVOLPLN_BUTTON			1158
#define IDC_DELVOLPLN_BUTTON			1159
#define IDC_EDITVOLPLN_BUTTON			1160
#define IDC_RESVOLPLN_BUTTON			1161
#define IDC_VOLSCAN_PLANES_LIST			1162
#define IDC_CH1BUTTON                   32777
#define IDPANE_MEMORY                   32778
#define IDC_CH2BUTTON                   32779
#define IDC_CH3BUTTON                   32780
#define IDC_CH4BUTTON                   32781
#define ID_FILE_SAVEPARAMETERS          32788
#define ID_FILE_LOADPARAMETERS          32789
#define IDC_OPTIMIZE                    32791
#define ID_FILE_SAVEDEFAULTPARAMETERS   32792
#define ID_TOOLS_ZEROGALVOOUTPUTS       32793
#define ID_OPEN_LOGBOOK                 32797
#define IDC_ONETOONE                    32801
#define IDC_TWOTOONE                    32805
#define ID_TOOLS_SHUTTEROPEN            32807
#define IDC_FULLRANGE                   32808
#define IDC_COLORCOMBO1                 32809
#define IDC_COLORCOMBO2                 32810
#define IDC_COLORCOMBO3                 32811
#define IDC_COLORCOMBO4                 32812
#define IDC_NEWCHANNELDROPDOWN          32813
#define IDC_NEWHISTOGRAMDROPDOWN        32817
#define IDC_ONETOTWO                    32820
#define IDC_DOUBLESIZE                  32821
#define IDC_SAMESIZE                    32822
#define IDC_HALFSIZE                    32823
#define ID_LOGHISTOGRAM                 32825
#define IDC_LOGHISTOGRAM                32825
#define ID_TOOLS_SAVEWINDOWPOSITIONS    32826

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        240
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1158
#define _APS_NEXT_SYMED_VALUE           116
#endif
#endif
